### ISSUE TITLE
Drull and Tog'thar

### ISSUE THREAD

**Issue by Lichery** [cmangos/classic-db#101]
After rescue Tog'thar says O_o:
"Gimmie my dolly!!"
Drull does not say anything.
They must says:
Tog'thar:
![t](https://user-images.githubusercontent.com/24303693/28233031-be0d16ac-68fc-11e7-9d3b-db84052eeb38.jpg)
Drull:
![d](https://user-images.githubusercontent.com/24303693/28233033-c0222d56-68fc-11e7-880c-01bd0ca0b3ac.jpg)

**Comment by cala** [comment]
Hi. A bit more info like quest ID and creatures ID would be helpful.
