### ISSUE TITLE
Missing trigger

### ISSUE THREAD

**Issue by Lichery** [cmangos/classic-db#105]
Missing trigger for use item 21041 around "Drop-Off Point". Approximate coordinates 67.72 in Winterspring.

Also, please check that item 21041 can only be used if player have the buff 25688

**Comment by cala** [comment]
What is this trigger supposed to be (name, entry...)?

**Comment by Lichery** [comment]
I do not know, but the item can not be used

**Comment by NeatElves** [comment]
go  id=180659

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/937bcd777d63d01de0202946d3f12f6d78b23ab0
