### ISSUE TITLE
Wailing Caverns missing text

### ISSUE THREAD

**Issue by M2us** [cmangos/classic-db#114]
npc_text id 7183
Missing this line: **Even his former acolytes have been corrupted by their master's waking nightmare - transformed into the wicked Druids of the Fang.**

Hm, and this too: **Dubbed the ‘Wailing Caverns’, these natural caves were filled with steam fissures which produced long, mournful wails as they vented. Naralex...**

look full text)))

http://warcraft.blizzplanet.com/blog/comments/world_of_warcraft_dungeon___wailing_caverns#

**Comment by Saben65** [comment]
Who is this even supposed to be attached to? It doesn't have a gossip menu associated with it in my version of Classic-db or TBC-db

**Comment by M2us** [comment]
Innkeeper. When you using LFD to Wailing Caverns.
Yes, in mangos LFD doesn't work, but, in npc_text table this text are there.

**Comment by Zooke** [comment]
I'm confused, who says this in 1.12 ?

**Comment by Saben65** [comment]
It was added in [patch 1.5](http://wowwiki.wikia.com/wiki/Patch_1.5.0) (under User Interface) and removed in [patch 2.0.1](http://wowwiki.wikia.com/wiki/Patch_2.0) (under user interface).

**Comment by cala** [comment]
Ah yes, the dungeon infos gossip from innkeepers. We never implemented it to core but it was discussed years ago.
