### ISSUE TITLE
Quest The Horde Needs Purple Lotus! wrong text

### ISSUE THREAD

**Issue by M2us** [cmangos/classic-db#117]
The Horde Needs Purple Lotus! (id 8582) wrong text in OfferRewardText.

Must be: **A commendable effort, $C. I will measure these specimens for their appropriate usage and note your contribution. The purple lotus will then need to be properly stored until I am ready for them. As for you, if you are still available I should imagine that I'll still need more purple lotus. Please check back with me in a moment.** 

http://wowwiki.wikia.com/wiki/Quest:The_Horde_Needs_Purple_Lotus!

**Comment by cala** [comment]
Thanks, closed by https://github.com/cmangos/classic-db/commit/7eb4b01d720602eb2783945a4c7be57a4d844c17
