### ISSUE TITLE
Not full text in the page

### ISSUE THREAD

**Issue by M2us** [cmangos/classic-db#118]
Text in page_text id 1471 and 1490 not full

Must be: **Solomon,$B$BThe carrier of this decree has been granted official status as an acting deputy of Stormwind. You may use $Ghim:her; to find proof of the black dragonflight's involvement with the Blackrock orcs. Should such proof be found, this deputy shall return said proof to me in Stormwind, at which time I shall release the order to dispense sufficient millitary force to aid Lakeshire.$B$BRegards,$B$B$B$BHighlord Bolvar Fordragon**

**Comment by Saben65** [comment]
From the item [Wrynn's Decree](http://www.wowhead.com/item=11368/wrynns-decree)
