### ISSUE TITLE
Duplicate rows in gameobject_template

### ISSUE THREAD

**Issue by Swater96** [cmangos/classic-db#12]
There are more than 3000 duplicate entries for game objects, with the largest being the object "Wooden Chair" with 890 entries that have the same displayid and size. I think we should start cleaning up these tables, more than 30% of the entries in this table alone seem to be redundant.

```
SELECT COUNT(*), displayId, name, size
FROM gameobject_template
GROUP BY displayId, name, size
HAVING COUNT(*)>1;
```

![duplicates](https://cloud.githubusercontent.com/assets/540552/19833450/9eaf8b7a-9e07-11e6-8304-68109fabc984.jpg)

**Comment by Grz3s** [comment]
gameobject_template .. :-1: 
All _templates comming from WDB/Sniffs... and we should never ever remove them.

**Comment by cala** [comment]
I agree with @Grz3s. Templates comes from packets sent to the clients, so we are sure those are valid Blizz data (even if some seem redundant) and as such must not be removed.
