### ISSUE TITLE
Obsidion

### ISSUE THREAD

**Issue by Saltgurka** [cmangos/classic-db#123]
Quest http://db.vanillagaming.org/?quest=3566 is currently not completable since the rebranding of UNIT_FLAG_OOC_NOT_ATTACKABLE -> UNIT_FLAG_IMMUNE_TO_PLAYER, since the flag is never removed in the script.

There is supposed to be an event upon accepting the quest which we are currently also missing. It is described in wowhead comments and on wowpedia:

* http://www.wowhead.com/quest=3566/rise-obsidion#comments:id=418731
* https://wow.gamepedia.com/Quest:Rise,_Obsidion!

Dorius (Entry: 8421) should spawn upon quest accept and then have a chat before transforming into Lathoric the Black (Entry: 8391). Currently he spawns and walks to the altar, but then he doesn't do anything else. (dbscripts_on_creature_movement id=842101)

The secondary way of spawning Lathoric is by talking to the altar. It is unclear whether this should spawn Dorius and he should do his whole event, or if Lathoric should just spawn immediately. (dbscripts_on_gossip id=1282)
Currently for each time you click the gossip menu option another copy of Lathoric is spawned. The condition should be expanded to also check for existing copies of him before spawning.

Does anyone have sniffs of this event? If not, I will try to write the script based on guesswork and the information found on wowhead and wowpedia.

**Comment by Grz3s** [comment]
i have complete 3.3.x vid from this quest...

**Comment by cala** [comment]
I agree the whole event needs to be rewritten/improved. Could you please share this video of yours, @Grz3s ?

**Comment by Grz3s** [comment]
https://www.youtube.com/watch?v=BAmAVlzp5bc
starts at 8:12

**Comment by Saltgurka** [comment]
Thanks for sharing :)
I will write a script for this tomorrow (sunday) based on that video and on the script Trinitycore implemented

**Comment by Saltgurka** [comment]
Done here: https://github.com/cmangos/tbc-db/commit/6707b2651f4ddd276e422975a532bffa5676fab2
