### ISSUE TITLE
Redridge Drudger

### ISSUE THREAD

**Issue by Phatcat** [cmangos/classic-db#129]
> -- Redridge Drudger (2.4.3 Official Data)
('58001','580','4','0','10','0','0','0','0','0','1','-5','-6','0','0','0','0','0','0','0','0','0','Redridge Drudger - Random Say on Aggro'),
('58002','580','2','0','100','0','15','0','0','0','25','0','0','0','1','-47','0','0','0','0','0','0','Redridge Drudger - Flee at 15% HP'),

(I checked, he is not listed in creature_template_addon either)

Should also know Dual Wield. 
![billede](https://user-images.githubusercontent.com/1907820/28995456-c5d5fd24-79e9-11e7-8a09-bdbd06a8c962.png)

**Comment by Grz3s** [comment]
@Phatcat :+1:

**Comment by Phatcat** [comment]
Suggested fixes;

> ('58001','580','4','0','10','0','0','0','0','0','1','-5','-6','11','674','0','0','0','0','0','0','0','Redridge Drudger - Random Say on Aggro'),
('58002','580','2','0','100','0','15','0','0','0','25','0','0','0','1','-47','0','0','0','0','0','0','Redridge Drudger - Flee at 15% HP'),

or

> INSERT INTO `creature_template_addon` (`entry`, `mount`, `bytes1`, `b2_0_sheath`, `b2_1_flags`, `emote`, `moveflags`, `auras`) VALUES
(580,0,0,1,16,0,0,'674'),
