### ISSUE TITLE
Valea Twinblades - missing plaque text

### ISSUE THREAD

**Issue by RichardGe** [cmangos/classic-db#133]
in the Scarlet Monastery - Hall of Champions,
Valea Twinblades has no text on her plaque.
I assume this code should be added :  

`
INSERT INTO 'page_text' ('entry', 'text', 'next_page')
VALUES
(2177,'Valea Twinblades\nWarrior of the Scarlet Crusade\nCitizen of Alterac\nLast seen deep in the Eastern Plaguelands\n',0);
`

source :  
http://wowwiki.wikia.com/wiki/Valea_Twinblades

**Comment by bdebaere** [comment]
@RichardGe If you look at your other issue and the pull request I made, you can make your own for this.
