### ISSUE TITLE
Capital guards burned by braziers

### ISSUE THREAD

**Issue by RichardGe** [cmangos/classic-db#134]
I assume this is a known issue because obvious - but I see no ticket on it , so I open one

in several capitals where guardians are standing near brazier, they are burned by it. 

don't know if this should be solved on database side (by moving slightly the guards)...  or on the engine side with an immune to brazier

![image](https://user-images.githubusercontent.com/2279126/31522586-eb3a54b6-afae-11e7-9e47-93ad2b2113dd.png)

**Comment by Phatcat** [comment]
https://github.com/classicdb/database/issues/297

**Comment by killerwife** [comment]
Check the Faction of the GO. GOs with the new code determine hostility/friendliness for spells through this faction ID. So far fixing faction ID worked in every instance.

**Comment by RichardGe** [comment]
ok thanks, then I close this as it's duplicated -
note that I think remember that guards in Orgrimmar - Cleft of Shadow  have the same issue
