### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by Lichery** [cmangos/classic-db#147]
All demon trainers have english string: 
![bandicam 2017-10-26 19-25-40-578](https://user-images.githubusercontent.com/24303693/32064850-b5ac529c-ba83-11e7-9d84-717782935ab5.jpg)

this should support localization

**Comment by cala** [comment]
I need more details here because I don't see anything wrong right now.

**Comment by Lichery** [comment]
these lines can not be translated because they are not in the database

**Comment by Lichery** [comment]
for example NPC 5749

**Comment by cala** [comment]
Ok, I'm not familiar with text localisation. Can you provide the expect DB update so we can fix this, please?
