### ISSUE TITLE
The shadowy city could not see the building after it flashed

### ISSUE THREAD

**Issue by bluehelp1989** [cmangos/classic-db#159]
After the flashing of a wizard, a building can not be seen in a dark city or a copy, and it can pass through the door.
Request to fix the problem of the flash.

This problem appears in the 1.12 and 2.43 

Mmaps, VMap, maps, DBC are all extracted, but still can't solve this problem, ask for help!

photo:
https://imgur.com/QNHjXtD
https://imgur.com/btDqOhE
https://imgur.com/DkRBWha

**Comment by cala** [comment]
Thanks for your report. Unfortunately, it is unrelated to the database, you should open an issue for the core and provide at least a video.
