### ISSUE TITLE
Missing locales_areatrigger_teleport table

### ISSUE THREAD

**Issue by M2us** [cmangos/classic-db#164]
In a new DB realese you lost **locales_areatrigger_teleport** table with **entry** and **text_loc** = (Translation of strings into **areatrigger_teleport.status_failed_text**)

https://github.com/cmangos/classic-db/commit/89fd31fd7a18a6787e79cdeb9816a3038d583d1c

=(

And empty db_script_string table - need delete this table.

**Comment by cala** [comment]
`locales_areatrigger_teleport` is created by mangos.sql from core when creating the DB for the first time. As every `locales_*` table, it is not supported nor modified by Classic DB. The commit you are referring to was to keep in sync with core SQL updates.
Unless I misunderstood something, it is expected that this table is not in the FullDB SQL file.

**Comment by LordPsyan** [comment]
During core startup, it shows an error that the table is missing. Here is the sql for those needing it:
`DROP TABLE IF EXISTS `locales_areatrigger_teleport`;
CREATE TABLE `locales_areatrigger_teleport` (
   `Entry` INT(11) UNSIGNED NOT NULL COMMENT 'Entry of Areatrigger Teleport',
   `Text_loc1` LONGTEXT COMMENT 'Text of the status_failed locale 1',
   `Text_loc2` LONGTEXT COMMENT 'Text of the status_failed locale 2',
   `Text_loc3` LONGTEXT COMMENT 'Text of the status_failed locale 3',
   `Text_loc4` LONGTEXT COMMENT 'Text of the status_failed locale 4',
   `Text_loc5` LONGTEXT COMMENT 'Text of the status_failed locale 5',
   `Text_loc6` LONGTEXT COMMENT 'Text of the status_failed locale 6',
   `Text_loc7` LONGTEXT COMMENT 'Text of the status_failed locale 7',
   `Text_loc8` LONGTEXT COMMENT 'Text of the status_failed locale 8',
   PRIMARY KEY(`Entry`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='Areatrigger System';`
