### ISSUE TITLE
[Faction] Brood of Nozdormu didnt affect Anachronos player standing.

### ISSUE THREAD

**Issue by Purownage** [cmangos/classic-db#168]
Hello I've noticed that when you are revered with Brood of Nozdormu, Anachronos appear in green color but when you try to interact with him its still combat method not possible to talk to him to turn quests.

**Comment by cala** [comment]
Try opening the reputation tab of the character sheet (shortcut: U), right-click on Brood of Nozdormu, unckeck "At war".

**Comment by Purownage** [comment]
ok thanks for the feedback you can close theat everything work fine. ^^
