### ISSUE TITLE
Vanilla mob rare loot

### ISSUE THREAD

**Issue by killerwife** [cmangos/classic-db#2]
https://gist.github.com/killerwife/3a8d1e697baa046f37cb438e692c279f

@cala Sadly I am not allowed to export the world loot references you will see all over the file. This is how rare mob loot is supposed to be done, @mantislord spent a lot researching it so if possible, put it to good use and if you have time, reverse engineer the references yourself. Until XS says so, I promised not to share world loot.

**Comment by cala** [comment]
Thank you for sharing what you are allowed to share. :+1:
