### ISSUE TITLE
Too many sources of Thick Yeti Fur (12366)

### ISSUE THREAD

**Issue by MantisLord** [cmangos/classic-db#203]
We discovered a discrepancy with Thick Yeti Fur (12366) drops for q.3783 'Are We There, Yeti?' in Classic-DB data.

Apparently throughout Vanilla and in early TBC, this quest was annoyingly difficult to complete as the fur only dropped from two creatures:
7457 | Rogue Ice Thistle
7458 | Ice Thistle Yeti

Evidence of this is found in official 2.4.3 patch notes when the quest was made easier to complete since the item was added to Matriarchs/Patriarchs and skinning drop tables.

http://wowwiki.wikia.com/wiki/Patch_2.4.3
Winterspring Ice Thistle Matriarchs and Patriarchs may now drop [Thick Yeti Fur].
Skinning any Winterspring Ice Thistle yetis may now result in [Thick Yeti Fur].

Suggested fix:

DELETE FROM creature_loot_template WHERE entry IN(7459,7460) AND item IN(12366);
DELETE FROM skinning_loot_template WHERE entry IN(7457,7458,7459,7460) AND item IN(12366);

**Comment by Zooke** [comment]
Yeah, you would get really pissed off with the fur not dropping and finally go look it up and find out you'd been killing the wrong yetis.
Fun times.
