### ISSUE TITLE
Ghost-o-plasm Round-up

### ISSUE THREAD

**Issue by killerwife** [cmangos/classic-db#21]
Issue - Quest not scripted
http://www.wowhead.com/quest=6134/ghost-o-plasm-round-up
TrinityCore did a really poor job as well
https://github.com/TrinityCore/TrinityCore/issues/1656

Current Data -
Involved GOs - 177746, 177749
177746 has faulty data, because it is supposed to have LinkedTrap and Generic - Type 5 does not support that.

Mobs involved - 11560 Magrami Spectre

Auras involved - 25039, 17327, 18951 (responsible for colors)

Additional spells - 17321 17680, related to spawning/despawning
19588 - spawns 177746 and starts script
19571 - purpose unknown

Script video https://www.youtube.com/watch?v=sePmFrhyKdo&feature=youtu.be - credit to our @Grz3s 

Script description:

After using Item, two GOs spawn, magnets, and the miniaura LinkedTrap. After that on a timer mobs start spawning, where some ignore pack pulling. After specified time, GO despawns and mini-event ends.

Requesting Sniff data for GOs if possible. Likely will be scripted in Kalimdor Map Update, because there is no dummy creature involved.

@cala @evil-at-wow Take a gander at my research.

Proposed fix - Implement OnGameobjectCreate in core as hook, script event in map update. Change 177746 to type that supports LinkedTraps.

**Comment by evil-at-wow** [comment]
I'm fairly sure I've done that quest somewhere during WoTLK, so with some luck I should be able to get you at least the GO data from 3.x sniffs.

**Comment by cyberium** [comment]
I dont see the point to add that hook?
You need a way to start the event?
We dont have on spawn gameobject possibility?

**Comment by killerwife** [comment]
@cyberium No we do not. :)

**Comment by xfurry** [comment]
> We dont have on spawn gameobject possibility?

```OnObjectCreate(GameObject* pGo)()```

You can add this on Kalimdor map, and then script it there: https://github.com/cmangos/mangos-wotlk/blob/master/src/scriptdev2/scripts/world/world_map_scripts.cpp#L58

**Comment by killerwife** [comment]
@xfurry thx, i couldve sworn it was there somewhere, I just looked in wrong place apparently, dont mind my blindness

**Comment by evil-at-wow** [comment]
Unsurprisingly, @killerwife was correct that one of the involved GOs has wrong data in our database. So, would you prefer a GAMEOBJECT_TYPE_BUTTON (1) instead? :smile: 

I knew I did that quest at one point during WoTLK, and I have now been able to dig up some relevant data from my archives (all data below is from version 3.3.2 build 11403). The update field data for the two GOs in the SMSG_COMPRESSED_UPDATE_OBJECT is below, with a few annotations. It might be worth pointing out that they were in the same packet, and in fact that update packet only contained the spawns for the two GOs. So they are to be spawned together.

```
Gameobject: GUID 0xf11002b6520d1146 (Ghost Magnet)
  Position (x y z o) = (-2296.92 1346.58 64.0881 -0.881217)
  Object Type = 0x05
  Update field 0 = 0x46110d52
  Update field 1 = 0xb60210f1
  Update field 2 = 0x21000000 [Type]
  Update field 3 = 0x52b60200 [Entry]
  Update field 4 = 0x0000003f [Scale = 0.5]
  Update field 8 = 0x5f0b0000 [Display ID]
  Update field 13 = 0x0000803f
  Update field 14 = 0x0000ffff
  Update field 15 = 0x72000000
  Update field 17 = 0x010100ff

Gameobject: GUID 0xf11002b6550d1147 (Ghost Magnet Aura)
  Position (x y z o) = (-2296.92 1346.58 64.0881 -0.881217)
  Object Type = 0x05
  Update field 0 = 0x47110d55
  Update field 1 = 0xb60210f1
  Update field 2 = 0x21000000 [Type]
  Update field 3 = 0x55b60200 [Entry]
  Update field 4 = 0x0000803f [Scale = 1.0]
  Update field 8 = 0x1c0e0000 [Display ID]
  Update field 13 = 0x0000803f
  Update field 14 = 0x0000ffff
  Update field 15 = 0x72000000
  Update field 17 = 0x010600ff
```

Remember from last time that the Object Type above is what my parser spits out for the type of the thing that follows in the SMSG_COMPRESSED_UPDATE_OBJECT packet. So it's not the gameobject's type, but it means this is an update for a gameobject (5) and not say a player (4), creature (3) or item (1). 

The actual GO type and some other GO data is in the SMSG_GAMEOBJECT_QUERY_RESPONSE packets (offset column, hex data column, ASCII data):

```
0000:0000 | 52b6 0200 0100 0000 5f0b 0000 4768 6f73 | R......._...Ghos
0000:0010 | 7420 4d61 676e 6574 0000 0000 0000 0000 |  t Magnet........
0000:0020 | 0000 0000 0000 00b8 0b00 0055 b602 0000 | ...........U....
0000:0030 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0040 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0050 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0060 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0070 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0080 | 0000 3f00 0000 0000 0000 0000 0000 0000 | ..?.............
0000:0090 | 0000 0000 0000 0000 0000 00             | ...........

0000:0000 | 55b6 0200 0600 0000 1c0e 0000 4768 6f73 | U...........Ghos
0000:0010 | 7420 4d61 676e 6574 2041 7572 6100 0000 | t Magnet Aura...
0000:0020 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0030 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0040 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0050 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0060 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0070 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
0000:0080 | 0000 0000 0000 803f 0000 0000 0000 0000 | .......?........
0000:0090 | 0000 0000 0000 0000 0000 0000 0000 0000 | ................
```

As you can see, your Magnet is a GO with type GAMEOBJECT_TYPE_BUTTON (1), while the Magnet Aura GO is a type GAMEOBJECT_TYPE_TRAP (6), as expected I guess.

Enjoy, and happy holidays!

**Comment by killerwife** [comment]
\o/ thx @evil-at-wow 

Also I already have a prototype and the guy who fixed naxx is working on finishing it. I will use this data and will get back to you on that.

**Comment by killerwife** [comment]
https://github.com/cmangos/mangos-tbc/pull/166 As promised :)
