### ISSUE TITLE
Starting weapons are incorrect

### ISSUE THREAD

**Issue by ainslievaux** [cmangos/classic-db#215]
Update 1.10 broke starting weapon skills because the race/classMask columns in the `playercreateinfo_skills` table are not granular enough to deal with the different starting weapons that each Warrior/Hunter/Druid race gets. 

For instance, Human Warriors should know Axes, Maces, and Swords on creation, but are getting Axes, Daggers, Maces, Swords, 2H Axes, 2H Maces, and 2H Swords, because those are all the weapons Warriors might start with. 

Even after applying the correct `raceMask` and `classMask` settings, a Human Warrior ends up with more weapons than it should (e.g. Thrown), because Humans can also be Rogues, and Rogues can use Thrown on creation. 

The attached patch is ugly but it fixes the issue.
[fix-playercreateinfo_skills-starting-weapons.txt](https://github.com/cmangos/classic-db/files/2752771/fix-playercreateinfo_skills-starting-weapons.txt)

**Comment by Warlockbugs** [comment]
Thank you for your report.
Table `playercreateinfo_skills` is a new one and will be maintained directly by the core team, so any future reports regarding it should go to root cmangos issue tracker. It hasn't been applied to classic-db yet.
I confirm there was a mistake made at the stage of planning with being too trigger happy with masking. Its being reworked with a new revision.
Dual wield will be dialed back for ineligible characters with a db revision. As for the rest of "free" weapon training, let it be a late Christmas gift for those who got up early. :smile:

**Comment by cala** [comment]
Alright, thanks. I will let this issue open here until the new DB revision is made core side so we can keep track of this.

**Comment by Warlockbugs** [comment]
All mistakes should be fixed as of https://github.com/cmangos/mangos-classic/commit/0c4900f5dd8388ce9b4124ee281e3693b133cdce

**Comment by cala** [comment]
Thanks! 👍
