### ISSUE TITLE
Translate FR

### ISSUE THREAD

**Issue by darkmoi31** [cmangos/classic-db#222]
Hi,

where i can found translate fr of database cmangos or mangoszero

thanks in advance for your help

**Comment by AnonXS** [comment]
https://github.com/MangosExtras/MangosZero_Localised/tree/master/Translations/French, but not entirely compatible with cmangos.

**Comment by darkmoi31** [comment]
this translete isn't complete ...

**Comment by cyberium** [comment]
He tryed to help you and you didn't even say thanks.
This is not an issue if you need a translation prepare your DB and do a PR and will evaluate the need of including it or not.

"La prochaine fois essaye d'être un minimum poli."
