### ISSUE TITLE
Error Importing Updates/2329_jungle_toad.sql

### ISSUE THREAD

**Issue by jimmybrancaccio** [cmangos/classic-db#227]
When running ./InstallFull.sh for the Classic DB it gives an error:

```
Appending Updates/2327_fishing_loot.sql
Appending Updates/2329_jungle_toad.sql

ERROR 1064 (42000) at line 4: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INSERT INTO spell_script_target VALUES (24062, 1, 15010, 0)' at line 2

ERROR: cannot apply Updates/2329_jungle_toad.sql
```

This could be due to the work done in #148.

``` sh
$ git rev-parse HEAD
e252084d973f0aa09c90cb9598fc122d9e1d2d17
```

**Comment by Phatcat** [comment]
https://github.com/cmangos/classic-db/pull/226

**Comment by cala** [comment]
Duh... It's not like I wasn't warned about this by @Phatcat but still managed to not fix this on master branch before pushing... 😖 

Closed by https://github.com/cmangos/classic-db/commit/81e30ba76549336c2fad8d5c0b5ab75a1689acc2
