### ISSUE TITLE
FullDB.sql have importing issue

### ISSUE THREAD

**Issue by cyberium** [cmangos/classic-db#25]
Hello.
On my system when i run my used command InstallFullDB.sh i now have issue with last part of the fulldb file.

```sql
--
-- Dumping routines (PROCEDURE) for database 'mangos-classic'
--
DELIMITER ;;

# Dump of PROCEDURE script_npc
# ------------------------------------------------------------

/*!50003 DROP PROCEDURE IF EXISTS `script_npc` */;;
/*!50003 SET SESSION SQL_MODE=""*/;;
/*!50003 CREATE*/ /*!50020 DEFINER=`mangos`@`localhost`*/ /*!50003 PROCEDURE `script_npc`(npc_guid INT, npc_script_id INT)
BEGIN
    DECLARE PX FLOAT Default 0 ;
    DECLARE PY FLOAT Default 0 ;
    DECLARE PZ FLOAT Default 0 ;
    DECLARE PO FLOAT Default 0 ;
    SET PX = (SELECT position_x FROM creature WHERE guid = npc_guid);
    SET PY = (SELECT position_y FROM creature WHERE guid = npc_guid);
    SET PZ = (SELECT position_z FROM creature WHERE guid = npc_guid);
    SET PO = (SELECT orientation FROM creature WHERE guid = npc_guid);
    DELETE FROM creature_movement WHERE id = npc_script_id;
    INSERT INTO creature_movement (id,point,position_x,position_y,position_z,orientation,script_id, waittime) VALUES
    (npc_guid,1,PX,PY,PZ,PO,npc_script_id, 2000);

    UPDATE creature SET MovementType=2,spawndist=0 WHERE guid=npc_guid;

END */;;

/*!50003 SET SESSION SQL_MODE=@OLD_SQL_MODE */;;
DELIMITER ;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
```

I dont get extacly what is the need of that but seem it require more db priviledge.

>> Processing Classic database v1.8 'Lunar Festival'.
ERROR 1227 (42000) at line 675528: Access denied; you need (at least one of) the SUPER privilege(s) for this operation
ERROR: cannot apply Full_DB/ClassicDB_1_8_z2692.sql

**Comment by cala** [comment]
I don't get it on either of my systems, so I assume that the latest versions of MySQL require higher privileges to insert procedures. This is annoying as I was intending to add a few of them to simplify some of the basic updates that needs several predictible lines like removing a creature, adding a script to it and so on...

**Comment by cala** [comment]
> I dont get extacly what is the need of that but seem it require more db priviledge.

There is no *real* need of this, but this can reduce significantly the amount of work I have to do when writing an update for the database, especially for long ones like those I pushed the last few days.

**Comment by katz1** [comment]
I am getting the following error with MySQL 5.7:

```
ERROR 1370 (42000) at line 675526: alter routine command denied to user 'mangos'
@'localhost' for routine 'mangos.script_npc'
ERROR: cannot apply Full_DB/ClassicDB_1_8_z2692.sql
```

**Comment by cyberium** [comment]
@cala is -> http://stackoverflow.com/questions/18479418/super-privileges-for-this-operation
make sense for you?

It basicaly say that we have to remove
> /*!50020 DEFINER=`mangos`@`localhost`*/

Just tried and it work without for me

**Comment by cala** [comment]
Alright, got it.
