### ISSUE TITLE
Fluorescent Mechanostrider

### ISSUE THREAD

**Issue by killerwife** [cmangos/classic-db#27]
http://www.wowhead.com/item=13325/fluorescent-green-mechanostrider#comments

Unsure to which DB this belongs, we are missing this.

Spell ID: 17458

Anyone can make item_template for this? I am not very skilled with those.

**Comment by Zingzah** [comment]
I was fiddling with these a while ago and it includes all the mounts I could find with spells but no items attached.  Whether they should be put in the official release or just for those as an optional extra is another question.

[Unused Mounts.zip](https://github.com/cmangos/classic-db/files/705894/Unused.Mounts.zip)

**Comment by Grz3s** [comment]
look like gm gave it to player .. by mistake?:) (gm mount??)

**Comment by killerwife** [comment]
Yes, but that doesnt mean cmangos cant have it :D
