### ISSUE TITLE
Troubled spirits of Kel'theril quest 5245 script

### ISSUE THREAD

**Issue by killerwife** [cmangos/classic-db#28]
This quest has 4 GOs from which we loot 4 items.
Upon doing this, at each GO, 2 spirits should spawn and attack the player
Mentions of this in http://www.wowhead.com/quest=5245/deprecated-troubled-spirits-of-keltheril

select * from gameobject_template where entry in(175888,175891,175892,175893);

If someone could provide video or at least entries of creatures that would be helpful. Should be very easy, maybe some /say

**Comment by Rushor** [comment]
@killerwife : try it with select * from creature_template where name like '%highborn%'

**Comment by Grz3s** [comment]
yo...
got something that may help here..
https://www.youtube.com/watch?v=5q9DcUO-FKQ   starts from 2:35

P.S
You're welcome ')

**Comment by Rushor** [comment]
nice! so it's just a normal http://wotlk.openwow.com/npc=7523 suffering highborn

https://youtu.be/5q9DcUO-FKQ?t=164

**Comment by Grz3s** [comment]
its random summon:
- Suffering Highborne
- Anguished Highborne

**Comment by cala** [comment]
Question is : how are they spawned/summoned ? I don't see a trap GO related to those gameobjects and I did not find a summoning spell in the DBC either (only looked quickly, though).

**Comment by killerwife** [comment]
On use of GO. So dbscript_on_go_use. Also there are no spells indeed, but I have an extension ready so we can randomize between two entries in dbscript.

**Comment by cala** [comment]
Summoning with `dbscript_on_go_use` requires coordinates, meaning we have to do one script per spawned GO. I was asking because to avoid that, usually, things that spawn NPCs on interaction (use, kill, whatever) uses a spell summoning near the caster. So only the caster's template is to be scripted and works whatever is the caster position when the script triggers.

**Comment by killerwife** [comment]
Yes, I am aware of the limitation. I will look in spell.dbc when im home to see if there is a spell that summons given entries. At worst I can create a c++ script that will randomize it, but i think these dudes spawn in a static spot for each go.

**Comment by cala** [comment]
> I will look in spell.dbc when im home to see if there is a spell that summons given entries. 

There is none, I already check. So, I guess we are going for static spawn there.

**Comment by killerwife** [comment]
Well either that or a c++ snippet. It all depends on whether it should be a static spot or multiple places around same GO.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/7e709ed3da12c75c28e96110a12c22b204c0346d
Thanks all of you.
