### ISSUE TITLE
Ravenwind Signpost- go.152580

### ISSUE THREAD

**Issue by killerwife** [cmangos/classic-db#29]
This GO seems to have wrong quaternion/spawn. 
This screenshot is what led me to this assumption http://imgur.com/jJqUquA

Currently http://imgur.com/a/l8DZ6 looks like this after porting quaternion from classic-db to tbc. wotlk-db one is basically the same just with different coords/placement.

Should anyone have this in their sniff, would be nice :)

PS: If I am littering classic-db with bad issues, tell me to stop.

**Comment by Rushor** [comment]
maybe the orientation is wrong?

**Comment by Rushor** [comment]
tc position for it:

```sql
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES (49843, 152580, 1, 357, 1108, 1, 1, -4446.32, 2055.25, 44.9976, -1.20428, 0.468413, 0.332221, -0.472813, 0.668331, 900, 100, 1, 0);
```

**Comment by killerwife** [comment]
@Rushor yours is under texture for me so even worse

**Comment by Rushor** [comment]
hm then it's a core issue

**Comment by killerwife** [comment]
Quaternion is sent directly to client. How can that be core issue.

**Comment by Rushor** [comment]
the db entries for the go are sniffed for tc as far as i know

**Comment by Tobschinski** [comment]
Looks like this is the reason it was moved.

![untitled](https://cloud.githubusercontent.com/assets/4753528/25177842/af3b0e1e-2503-11e7-9acb-6bd7ab1fc4a1.png)

**Comment by cala** [comment]
@killerwife while looking at this issue, I saw that you made this: https://github.com/cmangos/tbc-db/commit/b281f0a3eaf2f71c1a0da8b61102916cb6faf341 that is basically what we already have in Classic DB. Does this mean that I can close this issue?

**Comment by killerwife** [comment]
Yes, absolutely. I haven't found any other data on the subject and as such this seems to be the final fix.

**Comment by cala** [comment]
That was quick! 😆 
Thank you! 👍
