### ISSUE TITLE
Wrong Objectives for quest 'The Orc Report'

### ISSUE THREAD

**Issue by Muehe** [cmangos/classic-db#32]
The Objectives field of quest 1219 sends you to Lieutenant Aden. That NPC was added in TBC and the quest is finished by "Theramore Lieutenant" (4947). [See Twinhead page](https://vanilla-twinhead.twinstar.cz/?quest=1219) and the associated bug report.

http://www.wowhead.com/npc=23951/lieutenant-aden

**Comment by cala** [comment]
👍
