### ISSUE TITLE
Quest "Saving Yenniku" has wrong MinLevel

### ISSUE THREAD

**Issue by Muehe** [cmangos/classic-db#36]
```
-- Fix wrong MinLevel of "Saving Yenniku" 
UPDATE `quest_template` SET `MinLevel`='39' WHERE `entry`='592';
```

QuestLevel is 46, current MinLevel is 30, same as wowhead.  Affects TBC/WotLK too I think.

Source for MinLevel 39: https://web.archive.org/web/20060416013418/http://wow.allakhazam.com/db/quest.html?wquest=592
Ref: https://github.com/AeroScripts/QuestieDev/issues/392

**Comment by Tobschinski** [comment]
The entire quest chain has a minimum level of 30, wouldn't make much sense to not use it for this one. 30 is also confirmed here:

![bla](https://cloud.githubusercontent.com/assets/4753528/22499858/74464500-e861-11e6-8818-d4afb99d66b2.png)

**Comment by Muehe** [comment]
I see, thanks for the info!

**Comment by evil-at-wow** [comment]
@Tobschinski That looks like it's part of a magazine or book or something like that. Would you mind sharing some more details about that, assuming you know the source yourself?

**Comment by Tobschinski** [comment]
https://www.amazon.com/World-Warcraft-Master-Guide-Second/dp/0744008190
