### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by killerwife** [cmangos/classic-db#48]
https://www.youtube.com/watch?v=OE8Q9DVBdxc&feature=youtu.be

This video is a promotion for an upcoming TBC server. It contains a buttload of scripts in vanilla. It is worth looking to see what classic-db is missing :)

Tagging @cala and @Grz3s

**Comment by Grz3s** [comment]
Hi @killerwife 
Very nice video...  I'm happy that u used them detailed small or bigger events ... that many ppl wont even see during gameplay ( but they're important for ppl like me who .. loved every small detail of warcraft story)
I'm also happy that lots of recorded scripts here... are actualy done by me;] .... 
- here a small task for you and your mates... 
.. One of recorded scripts is unfinished ..and recorded with that error .. (I simply had no time... and later a forgot about it)...  .. Just wonder if you guys know ...which one :) ?

Anyway... 
I with you and your team... best ..  (from YT comments... I see that ppl are interested with it... some even looks like don't belive that, this can be true) :+1:

**Comment by killerwife** [comment]
Small misunderstanding: thats not my team :D But should I ever talk to the developer ill let them know. If my team gets to anything from the vid, ill make sure its exported asap :)

**Comment by cala** [comment]
Thanks @killerwife for sharing this. Like @Grz3s said, some of these changes are already in Classic/WotLK DB (sometime in a partial way) and some are missing. I'll add the Classic missing ones (hoping this videos will not be removed in a near future).

**Comment by Saben65** [comment]
Video was removed.

**Comment by cala** [comment]
Video has indeed gone private. Sad.
