### ISSUE TITLE
Rethban Gauntlet

### ISSUE THREAD

**Issue by killerwife** [cmangos/classic-db#49]
I was researching a bug with this quest and there seems to be a missing Debuff applied on quest accept - this aura supposedly makes you drunk as hell. Also we are missing the "quest fails if you die and release" part. But thats more of a core issue, since we have no way of scripting it right now.

**Comment by killerwife** [comment]
@MantisLord Discovered the spell ID. Once I figure out how to do the "failed on death" we will duke this out publicly.

**Comment by cala** [comment]
Thanks. :+1:

**Comment by cala** [comment]
Any update (no hurry, just to know)?

**Comment by killerwife** [comment]
Haven't gotten to making any on death event draft. The spell part is this though
-- The Rethban Gauntlet
UPDATE quest_template SET StartScript=1699 WHERE entry=1699;
DELETE FROM dbscripts_on_quest_start WHERE id=1699;
INSERT INTO dbscripts_on_quest_start (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(1699, 0, 15, 8554, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Cast Drinking Barleybrew Scalder');
Author @MantisLord
