### ISSUE TITLE
Monument to Grom Hellscream

### ISSUE THREAD

**Issue by Phatcat** [cmangos/classic-db#5]
https://youtu.be/UDQyEe06Q-M?t=19m34s

A few empty lines are missing on cmangos

(located in ashenvale)

**Comment by cala** [comment]
Assigning myself.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/ae4da39678ba10f75fae970e3fb9b1fc0606ae03
Thank you!

**Comment by cala** [comment]
What am I thinking of? I say that I assign myself but forget to do so, and then, I say that the issue is closed, but I don't close it. Need holidays, maybe?

**Comment by Phatcat** [comment]
Yes. Always more vacation =)
