### ISSUE TITLE
Linked spawns on timers.

### ISSUE THREAD

**Issue by Zooke** [cmangos/classic-db#52]
Something that needs implementing.

https://github.com/cmangos/classic-db/commit/c8634435c773b9ac98aaf7bb4cfd00c2ed15b86a Set spawntime ranges for few creatures

Probably useful for the 4 Alliance Outrunners in The Barrens too.

**Comment by killerwife** [comment]
Those outrunners have linkage which works for them I think, i.e. respawn when master respawns.

**Comment by cala** [comment]
Seems to be working.
