### ISSUE TITLE
Blackrock Depths - Dark Keeper Portrait doesn't spawn

### ISSUE THREAD

**Issue by RichardGe** [cmangos/classic-db#54]
In Blackrock Depths,
when you read the Dark Keeper Nameplate, it should randomly spawn one of the 6 Dark keepers

see comments here:
http://db.vanillagaming.org/?item=11197#wh-comments

for example, here it should spawn Dark Keeper Vorfalk... but it doesn't spawn.

![image](https://cloud.githubusercontent.com/assets/2279126/26036420/bb96ead2-38dd-11e7-8cc7-492a17d36329.png)

**Comment by RichardGe** [comment]
after another try, I realize that this was because the Dark Keeper Portrait was not there

In my second try, the Portrait was here, and I was able to kill Dark Keeper Zimrel
![image](https://cloud.githubusercontent.com/assets/2279126/26073964/94971f00-39b0-11e7-881b-9a6b40c05289.png)

So my question is: why it didn't work the first time? Why no Dark Keeper Portrait?  Maybe it's specific to Dark Keeper Vorfalk ?

**Comment by cala** [comment]
There is a bug in the pool system. When using a pool of pools, in some cases (currently undefined), there is no object/creature spawned while there should be one.

Thus, I'm closing this issue as it is a more generic core issue.
