### ISSUE TITLE
"The Great Masquerade" quest - transform Lady Katrana Prestor to Onyxia

### ISSUE THREAD

**Issue by RichardGe** [cmangos/classic-db#55]
in The Great Masquerade (6403) quest.  All the script is working correctly (nice work btw)

I have seen only 1 error:  Lady Katrana Prestor is supposed to be transformed into Onyxia, not a simple dragon.

Here is what I have with cmangos :
![image](https://cloud.githubusercontent.com/assets/2279126/26368902/574fabaa-3ff3-11e7-95d0-dce36d008ba2.png)

Here is the original quest :
https://youtu.be/myj4g07wb88?t=1m51s

**Comment by cala** [comment]
I'm pretty sure the change to the actual Onyxia dragon model was made in TBC (the linked video is from TBC). In Classic, Onyxia indeed used that dragonkin model for the Great Masquerade quest:
https://github.com/classicdb/database/issues/119

**Comment by RichardGe** [comment]
oh ok, I didn't do this quest in the past, so I have no idea.
so yes, maybe this is not an issue actually.

**Comment by Tobschinski** [comment]
No idea ... I was horde.

**Comment by Tobschinski** [comment]
https://youtu.be/xFG_bS9PaVA?t=83

**Comment by cala** [comment]
Fine. It was probably changed in late 2006 then because I made it several times with my Alliance characters until some time between AQ and Naxx release and it always was the dragonkin caster at these times.
Thanks @Tobschinski
