### ISSUE TITLE
Islands south of Tanaris

### ISSUE THREAD

**Issue by Phatcat** [cmangos/classic-db#6]
1 -9619 -5594 -496

There are a couple of islands located quite a bit south of Tanaris, these are supposed to have mobs here, birds and pirates and scorpids... or... pirate, bird and scorpid, cause I actually only spotted one of each;
https://youtu.be/UDQyEe06Q-M?t=16m50s

Looked a bit more and found at least one more pirate.
https://youtu.be/mDlaWZQsf7A?t=6m43s

Yet another video;
https://youtu.be/mVBNh94a3Cg?t=8m46s

http://wowwiki.wikia.com/wiki/South_Seas_islands
^
This one says hyenas as well.

**Comment by RichardGe** [comment]
I confirm what @Phatcat is saying. the 2 islands should be populated with NPCs
A good point it that Freshly Dug Dirt - object=180652 - for AQ door opening   is here .

Here is a more detailed source from "Wow Cartographe" with database v1.07 - version just before Burning Crusade release.

![mangos_2islands](https://user-images.githubusercontent.com/2279126/31522237-14b584d4-afad-11e7-8d59-4bf95357d9b9.png)
