### ISSUE TITLE
BWL updates

### ISSUE THREAD

**Issue by cala** [cmangos/classic-db#61]
Here are a few things that need to be improved in BWL:
- [x] ~~Grethok the Controller (Razorgore encounter) does not play his casting emote when facing the orb of command. Either the spell or the emote is missing~~
- [x] ~~Nefarian appears right on the plateform instead of flying and landing. His waypoints at the beginning of phase 2 are probably missing~~
- [ ] The Death Talon Overseers are missing their waypoints
- [x] ~~The Blackwing Technicians that are taking care of Vaelastrasz do not flee when players enter the room: their waypoints are also missing~~
- [x] ~~The suppression device do not play their fume animation~~
- [x] ~~Blackwing Taskmaster are missing their way-points and probably their interaction with nearby dragons~~
- [x] ~~Death Talon Captain's Mark of Detonation targets allied minions in combat, not hostile~~
- [x] ~~The first door (176964) in BWL should close whenever a boss-fight is in progress. (Just for the record, when you pull two bosses, the door is still closed and not open again, so please get rid of go-toggling and just close the door)~~

There are probably others issues, but those are the most obvious one from a quick run. By any chance, @Tobschinski do you have some data for BWL, please?

**Comment by Tobschinski** [comment]
NPC 12557 (Grethok the Controller) casts spell 23018 (Use Dragon Orb), which only hits NPC 14449 (Blackwing Orb Trigger) and causes the trigger to cast spell 23014 (Possess) on NPC 12435 (Razorgore the Untamed)

**Comment by killerwife** [comment]
I honestly hope that the suppression device fume aura is not cast by a GO and that there is a dummy creature, else that is gonna be a problem.

**Comment by cala** [comment]
@Tobschinski thanks!

@killerwife I don't know if the fume comes from a spell cast or a custom anim state of the GO. But you are right, if this is the former, it will have to wait for GO casting to be implemented.

**Comment by Tobschinski** [comment]
The start of the 2nd phase of Nefarian is indeed totally different from what you currently see in cmangos.

First of all, Nefarian spawns with unitflag 33554496 (which makes [this](https://github.com/cmangos/mangos-classic/blob/master/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/blackwing_lair/boss_nefarian.cpp#L138) obsolete)

When he does, he also yells - ```Well done, my minions. The mortals' courage begins to wane! Now, let's see how they contend with the true Lord of Blackrock Spire!!!``` - at one of the Drakonid Spawners.

Furthermore, he has 3 auras

__22992 - Shadow Flame__
It takes 10 seconds for the Shadow Flame effect to trigger and about 10 seconds for Nefarian to get to his last way-point, so the spell will be cast when he is still in the air. He will also yell - ```BURN! You wretches! BURN!``` - then. (so casting it [here](https://github.com/cmangos/mangos-classic/blob/master/src/game/AI/ScriptDevAI/scripts/eastern_kingdoms/blackwing_lair/boss_nefarian.cpp#L145) is not correct.)

__25184 - Speed Burst__
Not sure why Blizzard used a spell to increase his run speed. Of course, Nefarian should be faster in the air than he is on the ground, but they never remove this spell, they just lower his run speed from 30 to 15 exactly 10 seconds after spawning. The aura persists.

__19818 - Double Attack__
self explanatory

Spawn location is unknown, he is too far away when he does, way-points are:
[0] X: -7348.849 Y: -1495.134 Z: 552.5152 (could be a calculated one, not sure, very close to point 1.
[1] X: -7348.540 Y: -1494.183 Z: 552.5152
[2] X: -7392.868 Y: -1475.698 Z: 544.6193
[3] X: -7423.417 Y: -1437.656 Z: 535.3140
[4] X: -7445.253 Y: -1402.114 Z: 523.8420
[5] X: -7460.383 Y: -1372.600 Z: 513.0922
[6] X: -7479.808 Y: -1331.756 Z: 498.7586
[7] X: -7492.582 Y: -1295.351 Z: 488.0915
[8] X: -7502.002 Y: -1256.503 Z: 476.7582 (end point)

After his yelling, burning and whatever he's also doing is done, he performs a OneShotLand (293), which activates gravity and stops his hovering. When that is done, he finally starts attacking (remove not-selectable-flag here)

**Comment by Tobschinski** [comment]
The Suppression Devices continuously cast spell 22247 on an exact 5 second timer. When they do, they also play a custom animation.

I am not sure right now what causes the offset you see in many videos. Not all GOs cast at the same time.

**Comment by killerwife** [comment]
But the GOs or dummy creatures near it?

**Comment by Tobschinski** [comment]
The GO itself.

**Comment by Tobschinski** [comment]
Another issue I can see is about NPC 12467 (Death Talon Captain). Their aura 22436 (Aura of Flames) targets allied minions in combat, not hostile. And they will just kill the Captain, rude.

**Comment by Tobschinski** [comment]
Got you some more homework @cala .

**Comment by killerwife** [comment]
Ugh, I had the same issue with GO casting in Shattered Halls during Gauntlet. They cast with 5 second timer too. I disguised the packets as if they were sent by GO and i used dummy creature to cast them, but its a horrible temporary workaround....

**Comment by cala** [comment]
Thanks again @Tobschinski I'll do my homework.
 For BWL, I think the spell is cast by GO because they are trap GO. From what I saw, spell 22247 is indeed cast, only the visual is missing. Or at least, the trap triggers spell 22247 when player is nearby. I need to investigate further how this is currently working in cmangos.

**Comment by killerwife** [comment]
You are right, it will work like that. It just wont trigger every 5 sec regardless of player being around.

**Comment by Tobschinski** [comment]
I have quite some trouble getting dragons to fly in vanilla. Maybe you have more luck.

**Comment by killerwife** [comment]
Its not a coincidence. MOVEFLAG_LEVITATE does not have a packet in vanilla/tbc. Try setting HOVER to mobs which start flying after a while. Thats how Nightbane works to this day on retail. Either that or InhabitType or the weird flag used in onyxia script.

**Comment by Tobschinski** [comment]
Maybe even something basic as rooting a creature mid-air, at least there is a spell for that 18430 - Dragon Hover - the floating eye in AQ40 which is overving the Twin Emps has it.

But I'll definitely check out Nightbane, Onyxia, Nefarian, Sapphiron, they were all updated after WotLK, sadly.

**Comment by killerwife** [comment]
Yes but the underlying logic doesnt seem to be altered. Just a few more packets are being sent, thats all. The reason why this is happening is that we have wotlk code, I ran into issues when fixing Nightbane. Sadly I was not able to make a generic TBC flying draft :/

**Comment by Tobschinski** [comment]
Looking at it again, I remember what my issue was. The flying mob wouldn't STAY in the air while casting spells, it would constantly jump between air and ground phase.

**Comment by killerwife** [comment]
The Hover state change should fix it.

**Comment by Tobschinski** [comment]
no such luck

**Comment by cala** [comment]
I have the same issue with Onyxia that I noticed when doing this: https://github.com/cmangos/mangos-classic/commit/844460bc7583c70cf64a6c4ffe22de4249a10384
She looks like standing in the air when she should be hovering. If you have any suggestion of where I should start to fix this @killerwife ?

**Comment by cala** [comment]
@Tobschinski I'll be in holidays starting next week. I'll take care of adding your data into SD2 when I'm back.

**Comment by cala** [comment]
Thank you for all your recent BWL updates.

**Comment by cala** [comment]
@Tobschinski Prepare yourself for incoming data requesting, questioning, harassing, fish throwing and maybe a bit of thanking: I'm now working on BWL.
https://github.com/cmangos/classic-db/commit/331fe629e1d7a9a809ee2676bac90668617e9128

**Comment by cala** [comment]
To centralise data from @Tobschinski :
> Razorgore does not cast spell 20037, NPC 14449 does. On death, Razorgore casts spell 23024, with NPC 14449 as a target.

**Comment by Tobschinski** [comment]
Razorgore's full heal in p2 is spell 23040, think that's missing as well.

**Comment by cala** [comment]
Thanks. It is indeed missing. That part is currently handled in the script instance, I'm wondering if I move it back to the Razorgore script.

**Comment by cala** [comment]
@Tobschinski can I bother you with two questions regarding Razorgore encounter?

1. Does Razorgore change faction during the fight (while being mind controlled for instance) ? We have faction 1114 in DB currently
2. Does GO 177808 (Orb of Domination) changes status during the fight ? Especially, does it changes its visual state ?

**Comment by Tobschinski** [comment]
Well, if you charm a unit it will get the faction of the unit it is getting charmed by.
GO 177808 doesn't do much, just set unitflags = 16  in p2.

**Comment by cala** [comment]
Ok, so (aside from having player faction while controlled) Ragorgore keeps it 1114 (Blackdragon Flight - Bait) all fight long.
Thanks for your confirmation.

**Comment by cala** [comment]
I need one last feedback actually. I'm working to implement proper resets in the fight (currently, depending on when the raid wipe, the encounter can be broken).

What happens if players wipes before killing Grethok but after Razorgore has cast conflagration on Grethok/his guardsmen? Do they all instantly evade once all players are dead or do Grethok/his guardsmen fight Razorgore until he or them are killed (and then everyone reset/respawn) ?

**Comment by Tobschinski** [comment]
Well, I can't tell you for sure ... but ...

Grethok and Razorgore do not share a faction, they will fight each to the death. I don't see the reason why they should evade when every player on their threat-lists are dead, they (in my opinion) evade when there is nothing in there at all. But as I said, I don't know, I would have to test this unique case.

However, threat is not kept when Mind Control runs off, I see Razorgore being removed from any nearby creature's threatlist when that happens.

**Comment by cala** [comment]
Ah ! The threat reset is probably the info I was missing. You mean that all NPCs have Razorgore removed from their threatlist when the Mind Control wears off? Thanks for the tip.

Regarding the specific case of Grethok, as it is a unlikely case to happen in most situations (unless the raid is very bad), don't waste time on this unless you really want to know.

**Comment by Tobschinski** [comment]
That should be the normal behavior of any controlled unit I think. When you control a creature and attack another, both should attack you after the effect ends. (afaik)

**Comment by cala** [comment]
I agree with you. Though I never controlled Razorgore on retail, I played priest and I remember the mobs behaviour when I MCed them.

We should ask to @cyberium who remade the possess AI code recently, but I don't think this is handled in CMaNGOS. At least not for Razorgore encounter.
Currently, the possessed NPC does not have full threat on its controller when it is released and I don't think that the threat generated by the possessed NPC against other NPCs is transfered to its previous controller when the mind control ends.

**Comment by killerwife** [comment]
It isnt transferred, because we don't know the blizzlike behaviour. @cyberium designed it in a way so that the possessed creature has all targets it cant attack removed(after its factions and flags are restored), and gets an amount of threat against its possessor (the one who cast charm/MC).

**Comment by cala** [comment]
Thanks for clarifying.

**Comment by cala** [comment]
> Death Talon Captain's Aura of Flames targets allied minions in combat, not hostile.

@Tobschinski After testing, I think Aura of Flames works as intended, this is the spell Mark of Detonation that is causing the issue because it damages the Captain and its allies making them aggro him (poor lad). I assume this uses the wrong target (the script currently target a random player).

**Comment by Tobschinski** [comment]
Wouldn't surprise me at all, I've seen a lot of friendly fire behavior recently, even twice in BWL.

**Comment by Tobschinski** [comment]
There's also an emote if you fail in p1, ```%s loses power and shuts off!```
Sender is Orb of Domination, but I can't tell you if it's creature 14453 being hidden somewhere (like Nefarian's troops) or the GO itself. Are GOs able to do emotes?

**Comment by cala** [comment]
Some updates:

**Death Talon Captain**
It is definitely the Mark of Detonation spell that causes the friendly fire. However, that issue persists whenever the spell is cast onto the captain or onto a player. Thus either:
-  `(TARGET_EFFECT_SELECT, TARGET_ALL_FRIENDLY_UNITS_IN_AREA)` is not working as intended (at least in this case) and targets everything in the area (players and NPCs alike)
- having a player being a GM (even with GM off) makes him/her being considered as friendly in this case
- the spell and  `(TARGET_EFFECT_SELECT, TARGET_ALL_FRIENDLY_UNITS_IN_AREA)` are working as intended but the NPCs are missing some aura/abilities (or fire immunity) that would prevent them from taking damage from the spell

**Orb of Domination emote**
Do you mean that if Razorgore is killed before all the eggs are destroyed, this emote is played?
The only DB I know of that has spawns of this NPC is wowd, one of the first WOW DB ever. There are several of them, on different locations across the room when one would expect the location (and spawn) to be unique. So I guess this NPC is spawned when a specific creature is killed and I would bet it to be Razorgore in P1.
But this is a wild guess and it is also possible to make an unspawned NPC perform a yell or an emote, though in CMaNGOs the later is not possible (yet).

**Comment by killerwife** [comment]
Well, to provide some clarification, its possible that faction ID or unitflags are wrong, or that the old API (the new one currently sitting in mangos-tbc/feature/relations) decides wrongly that the target is "assistable". Hopefully when @cyberium has time to merge/port it, your course of actions will be clearer.

**Comment by Tobschinski** [comment]
Cannot really tell you why or when it is played, but there's two emotes, one was when I killed Razorgore in p1, the other when I've successfully beaten it. This is in a very old .txt of mine, with half of the packets not even parsed.

But I have 

```
Message: %s loses power and shuts off!
Receiver: Razorgore the Untamed
Sender: Orb of Domination
```

and 

```
Message: %s flee as the controlling power of the orb is drained.
Receiver: Razorgore the Untamed
Sender: Nefarian's Troops
```

I want to re-run BWL again and test a couple of things, but TC's sniffer and parser are outdated.

**Comment by Tobschinski** [comment]
Mark of Detonation looks like another parent / child - spell misbehavior, we've seen a few more in the past few weeks.

**Comment by cala** [comment]
More updates:

**Emote in Razorgore P1**
I will spawn and despawn the NPC 14453  to perform the emote at the right time. I don't think it is spawned all the time.

**Suppression device**
I wanted to trigger all GO traps in the instance script but as long as we are missing GO casting in core, this is not possible. A temporary solution then is to trigger their visual animation instead, my first tries are promising.
Also the disarming of the GOs is not giving the expected results, but this is a core issue: we are not using the GOs as they should in this case and I'm working on a PR for that.

**Mark of Detonation**
Good shot, @Tobschinski the child caster is the original caster. Combat log shows that:
- Death Talon Captain is caster of parent spell with player as a target (as intended)
- Spell procs on player when hit in melee (as intended)
- Child spell has Death Talon Captain as caster which logically damages himself and allies, initiating the friendly fire.

So this clearly looks like a core issue in the spell system rather than a relation issue. I'll try to investigate that also.

**Comment by cala** [comment]
@Tobschinski 
> The Death Talon Overseers are missing their waypoints

Could you tell me if the various Death Talon Overseers seen in [this video](https://www.youtube.com/watch?v=bwkmQfjqxH8) at [6:12](https://youtu.be/bwkmQfjqxH8?t=6m12s), [6:13](https://youtu.be/bwkmQfjqxH8?t=6m13s), [6:29](https://youtu.be/bwkmQfjqxH8?t=6m29s) and [6:31](https://youtu.be/bwkmQfjqxH8?t=6m31s) do have waypoints on retail or random movement (like currently in CMaNGOS), please? Thank you! :)

**Comment by cala** [comment]
Another question for @Tobschinski  or @evil-at-wow is about the Thrash abilities of Firemaw, Ebonroc and Flamegore. Wowhead and the like say it is spell 3391 which is a single shot spell while Thrash is usually handled by an aura that triggers spell 3391 on proc.
My question is:
- is it indeed spell 3391 with a timer to periodically cast it (and so, what is the timer) or do the three drakes use another spell that triggers 3391 ?

**Comment by Tobschinski** [comment]
Raidbosses almost always use thrash with timers. Otherwise, bad luck could easily kill you. I will see if I can tell you how often it is being used.

They have waypoints, but it isn't always the Overseers.

**Comment by cala** [comment]
Oh! The teasing...

**Comment by cala** [comment]
Regarding the thrash timer, WoW dungeon companion hints that the thrash ability occurs some time after the Shadow Flame and that healers must be on top of that. So maybe we are not looking at a standalone timer for thrash but for a timer starting from Shadow Flame cast (just an idea)?

**Comment by Tobschinski** [comment]
Nah, looks more like this guy is continuously thrashing, 2-6s. I know I have more data collected, I'll try to look for more info.

**Comment by Tobschinski** [comment]
__Chromaggus__

1. Chromaggus isn't able to take control of more than one player. That is probably an issue for @cyberium 
2. Brood Affliction: Bronze stun procs every 5 seconds, that is of course wrong. I'd guess it's a 10% chance to get stunned.
3. Every 7 seconds, Chromaggus casts 23173 - Brood Affliction. The spell choses one random Afflication and cast it 15 times on random players. These targets are not unique, if you for example solo the boss, you will get hit 15 times at once, (so no use of @killerwife 's recent work here)

**Comment by cala** [comment]
The third point is taken care of in https://github.com/cmangos/mangos-classic/commit/0fe0518b0d7cdac8f33f1677e6b7e8ec18e22eb5
I'll look into point 2 soon.

**Comment by cala** [comment]
Point 2 handled here: https://github.com/cmangos/mangos-classic/commit/5066fb3a1c452699f27dc4da09f0f721f0ddd006

Point 1 is out of my league.

**Comment by killerwife** [comment]
Is it by any chance AOE charm spell?

**Comment by cala** [comment]
I can't tell for sure right now but I don't think so. I'll confirm this to you tomorrow when I'll give this spell another look for the two additionnal spells when mutated.

**Comment by killerwife** [comment]
Please do, because i encountered such spell on leotheras the blind.

**Comment by killerwife** [comment]
The spell used is 23174 which indeed is a normal charm. But judging based on blizzards hackiness in vanilla, and AOE charm not being implemented much later on (first used in naxxramas vanilla), my best guess is that it should be an aoe charm, at least internally.

I don't know if I exported my code yet, but the most propable fix will be to make it behave like an aoe charm, even if only internally. Those for a fact can be more per target.

**Comment by cala** [comment]
The spell is a single target for the charm effect, indeed.
I don't know if there was some specific way to handle the mind control for that spell in Classic times in regards of Kel'Thuzad AoE mind control (different spell effect).

It is also possible that this is a limitation of the charm/possess system in the core that does not handle this specific case.

Another possibility is that Chromaggus can only control one player at a time.

**Comment by killerwife** [comment]
My guess is that blizzard added functionality of "more charms per one" in vanilla as a prototype on chromaggus, and just never changed client spell.dbc when they made the AOE charm type. They have made such decisions in other areas of the game. Clientside there is no difference between aoe charm and normal charm.

**Comment by cala** [comment]
@Tobschinski I'll request your inputs here one more time.

**Drakonids spawners**
I now use the same way to select which drakonid spawner will be used that for Chromaggus' breaths. I added an AI to each spawner to spawn a chromatic drakonid every 60 s (via spell 22680) and they also have aura 22653 which triggers 22659 that will cast 22654-22658 depending on which one of the five spawner is casting. I don't know if 22652 is used.

Unfortunately, that does not work. Chromatics drakonids are spawned anywhere (probably due to spell 22680 having an effect radius of 100) and red/blue/black/... drakonids are not spawning. Can you tell me if my approach is supposed to be correct or if things are done differently on retail ?

**Shadowblink**
Current CMaNGOS script have Lord Victor Nefarius casting various versions of Shadowblink but none of them seem to be scripted. I would appreciate any hint about those spells (22664, 22668-22676, 22681)

**Shadowflame**
You say that Nefarian spawn with 22992. This is a periodic AoE Shadowflame, is the aura removed at some point (landing)?

Thanks!

**Comment by Tobschinski** [comment]
Spell 22992 has a duration of 11 seconds.

I'll see about the rest when I'm home ...

**Comment by cala** [comment]
> Spell 22992 has a duration of 11 seconds.

You can call me an idiot: I missed that point when looking at the DBC.

**Comment by Tobschinski** [comment]
Idiot.

**Comment by Tobschinski** [comment]
Nope, Chromatic Drakonids are indeed summoned with spell 22680.

**Comment by cala** [comment]
So, my approach is Blizzlike. All cast from the spawner, I guess. Then, I have to understand why they do not spawn in the tunnels, near the spawner NPCs...

**Comment by Tobschinski** [comment]
Can't really tell you, the owner of these creatures is hidden. But it is most likely one of the spawners.

**Comment by Tobschinski** [comment]
What I can do is check the coordinates of spawning creatures and see if I can get something from that.

**Comment by cala** [comment]
If you can do so, that will be nice please. In the meantime, I'll force the spell radius to zero to ensure the drakonids are spawned inside the tunnels.

**Comment by cala** [comment]
Nefarian is taken care of in https://github.com/cmangos/classic-db/commit/4970babf300922f029fa66b71708aa40a3643992. The only thing that remains on the list is:
> The Death Talon Overseers are missing their waypoints

@Tobschinski  you said:
> They have waypoints, but it isn't always the Overseers.

If you can provide more data, I'll be happy to add them, otherwise, I will (finally) close this issue. 😄

**Comment by Tobschinski** [comment]
Will check.

Is the damage reduction applied to Razorgore if he's controlled by players? Otherwise he can be used to kill the attacking orcs easily .

**Comment by Tobschinski** [comment]
very soon...

**Comment by cala** [comment]
As long as it is sooner than what it took Blizz to release patch 1.10 for Diablo 2 LoD, I'm fine with it. ;-)

**Comment by Warlockbugs** [comment]
@cala 
You will be able to cross out Chromaggus' charm soon. I am finalizing a series of patches for multi-charm support.
![Imgur multi-charm screenshot](https://i.imgur.com/KNihy82.jpg?1)
