### ISSUE TITLE
NPC: Nazgrel (3230)

### ISSUE THREAD

**Issue by brotalnia** [cmangos/classic-db#62]
Nazgrel is spawned in the wrong spot. He should be on the other side of the room. Also the quest The Admiral's Orders part 2 (831) should be turned in to him in vanilla, not to Vol'jin. The quest text also needs to be updated to say Nazgrel where it says Vol'jin.

Proof:
His correct location - https://youtu.be/YcEqpVfrE7U?t=55m31s 
Read the quest text - https://youtu.be/YcEqpVfrE7U?t=10m21s

**Comment by cala** [comment]
@Tobschinski I see that you closed the issue while Nazgrel indeed seems off place judging by the linked video. I would tend to accept the related PR (https://github.com/cmangos/classic-db/pull/67). Do you have an objection?

**Comment by Tobschinski** [comment]
Nope.
