### ISSUE TITLE
 Quest: Resupplying the Excavation - is missing data

### ISSUE THREAD

**Issue by oppahansi** [cmangos/classic-db#71]
Hi,

after a good while of research and discussion with @Phatcat we ended up discovering several missing things in the DB for the mentionend quest Resupplying the Excavation (entry 273).

- NPC Saesan is currently not spawned in the world.
- SpecialFlags for Quest 273 is not set to 2.
- scripted_areatrigger is missing a script reference for the event script
- areatrigger_involvedrelation needs a reference to the Quest 273

cmangos currently does not have the script implemented.  PR for this and PR for the script implementation will go live at the same time. I will edit this later.

Implemented script:
https://github.com/cmangos/mangos-classic/pull/296

Sources used:
https://web.archive.org/web/20080406083214/http://thottbot.com:80/q273
https://web.archive.org/web/20060525060138/http://wow.allakhazam.com:80/db/quest.html?wquest=273

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/aa237c43ebf5260fd7ba463f9ae1cbe2bd1b617b
Thank you.
