### ISSUE TITLE
Ragnaros loot

### ISSUE THREAD

**Issue by killerwife** [cmangos/classic-db#75]
http://www.wowhead.com/npc=11502/ragnaros
http://www.wowhead.com/npc=11583/nefarian

DELETE FROM creature_loot_template WHERE entry IN(11502) AND item=34107 AND mincountOrRef=-34107;

Wrong items.

**Comment by Tobschinski** [comment]
me no comprende

0 row(s) affected

**Comment by killerwife** [comment]
What a beautiful and magnificent derp.
