### ISSUE TITLE
small error in page_text

### ISSUE THREAD

**Issue by Lichery** [cmangos/classic-db#78]
entry 79:
... The agent in charge of these gatherings, **"The Collector,"** will be known by the engraved ring he possesses ...

entry 197:
**"dearest,"** and **"my love,"** and ..

entry 198:
"I'll take you.  All of you,"

entry 199:
"Please,"

entry 201:
"This woman lies,"

entry 266:
"brethren,"

entry 281:
"the Forsaken,"

Comma must be after quotes:
"**,**

omg... There are so many mistakes ...

**Comment by Muehe** [comment]
Seems this problem is not only present in the `page_text` table. Related queries:

```sql
SELECT * FROM page_text WHERE text LIKE '%,"%'; -- 8 rows returned

SELECT * FROM quest_template 
WHERE Details LIKE '%,"%'
OR Details LIKE '%,"%'
OR Objectives LIKE '%,"%'
OR OfferRewardText LIKE '%,"%'
OR RequestItemsText LIKE '%,"%'
OR ObjectiveText1 LIKE '%,"%'
OR ObjectiveText2 LIKE '%,"%'
OR ObjectiveText3 LIKE '%,"%'
OR ObjectiveText4 LIKE '%,"%'; -- 7 rows returned
```

By the way, does anybody know why the `page_text` table uses U+000A for line feeds, instead of the placeholders used in the text fields of `quest_template` ($B)?

**Comment by Lichery** [comment]
I dont know. I suggest changing the entire page_text table and using the usual $B placeholders : )

I found a bug in npc_text
9566: Yes, $t citizen : citizen;
I think there should be:  Yes, $g citizen : citizen;

**Comment by Grz3s** [comment]
Data from `page_text` comes from WDB cache...
https://github.com/cmangos/issues/wiki/pagetextcache%E2%80%8E
I don't think that any data there was made by hand by any dev...here.. 
I happens, that sometimes we see mistakes made by blizz devs... not only here.. but in any texts (example here: `db_script_string`) Some of them were also reported by players on WoWHead etc...

It is a good question ...(to DB Devs) if we want to change official data or leave it as it is...

Also.. I cant give u 100% that all our data is correct ... but until you'll show proof (WDB) from these entrys, We shouldn't change anything there (my opinion)

**Comment by cala** [comment]
> It is a good question ...(to DB Devs) if we want to change official data or leave it as it is...

@Grz3s that's a question we can also have with all broken spells or bugs that are/were in retail and that we could fix.

In my humble opinion, fixing small typo like those inverted quotes/comas are acceptable because they are harmless for the gameplay and they disturb the experience (I dislike myself to see those wrong texts). But I agree with you that we should ask other devs opinion on the matter to avoid having texts fixed in a DB and not in another.

**Comment by Saltgurka** [comment]
I support correcting minor mistakes in texts even though they may have been wrong on retail in the first place. Correct grammar and spelling can only have a positive effect on the game imo, and it does annoy me each time I see something like that while playing.

**Comment by bdebaere** [comment]
I agree with @Saltgurka, I also have a gossip from an NPC which is clearly wrong grammatically. If you google it you find sources stating it is also wrong on retail, and a forum post from a player which says it's wrong grammatically like I said.

**Comment by cala** [comment]
@cyberium , @Grz3s and @killerwife what is your opinion about fixing typos in quest or NPC texts that are obviously wrong, even if it was also wrong on retail? Do we aim for 100% blizzlikeness even if it means keeping bugs and errors or do we sacrifice a bit of blizzlike for the sake of gameplay?

**Comment by cyberium** [comment]
We found a way to keep original data in the core about spell_template but we clearly decided that it was time to fix some known wrong spells.
I dont know for sure if its worth to keep original texts when they are wrong but my feeling say no.
So on my side clearly faulty sentence should/can be fixed directly in DB.

**Comment by killerwife** [comment]
Texts with typos are a big NO from my end even if its blizzlike. Feel free to let me know what u guys think. When it comes to core bugs, the line is blurry, because it used to enable some really nifty DPS mechanics in some patches. So there should never be a black/white stance on those.
