### ISSUE TITLE
Ratchet flagged as horde territory

### ISSUE THREAD

**Issue by Phatcat** [cmangos/classic-db#79]
It's a neutral town and should be flagged neutral. having it flagged as horde territory force enables pvp on for alliance players on pve servers, for visiting a neutral town in a neutral zone...

**Comment by Phatcat** [comment]
Okay that's so weird I was sure it said horde territory the other night.. now it says contested... nevermind I guess .

**Comment by Phatcat** [comment]
Nope, there is definetely something fishy going on. Taking the boat from ratchet to booty bay forces you into pvp as alliance by crossing several different horde territories;

(example)
![billede](https://user-images.githubusercontent.com/1907820/27744134-b0401644-5dbe-11e7-9bb1-f3415f915954.png)

which should probably be flagged contested, and also when you stand on the boat in ratchet (actually that spot where you can get caught between the peer and the boat) it says ratchet is horde territory;

![billede](https://user-images.githubusercontent.com/1907820/27744197-e299c1b2-5dbe-11e7-9653-b3e9393149ec.png)


Trying to take the boat back from booty bay to ratchet resulted in this....

![billede](https://user-images.githubusercontent.com/1907820/27744063-7565096c-5dbe-11e7-8f02-41d706ab0cde.png)

**Comment by cyberium** [comment]
The client crash is a core issue. Iam also almost sure that pvp tag issue is core one.

**Comment by Phatcat** [comment]
I just assumed anything to do with.. content, such as different zones, wouldn't be hardcoded and be handled db side. Want me to move the issue to the centralized core issue tracker?

**Comment by killerwife** [comment]
The flag is not per town, it is per zone. When going to ratchet you will inevitably be flagged as pvp because Barrens is a pvp zone (i dont remember if horde or contested, same outcome for alliance char). That is why Ratchet has Neutral guards, albeit with worse coverage than Booty Bay.

**Comment by Phatcat** [comment]
Well, I just noticed I can't speak about force flagging on pve as my server is set up as a pvp server and I can't seem to find where I edit this, but I tell you this much, back in retail, the only zones that would force flag you for pvp was enemy zones, and the only enemy zones in the game are starting zones for the enemy faction, contested zones force flag you for pvp only on pvp servers, where 'safe zones' don't flag you for pvp on any kind of realm. Or should, at least...

**Comment by cala** [comment]
@Phatcat: I agree with you about content issues being outside of core by default. However in this case I think the issue comes from the DBC files (or the way the core handle them) because I don't think areas are handled at all DB side. Hence it is probably a core issue (and this reminds me that I still don't know if having two separate trackers for core and DB issues is a good thing)

**Comment by Phatcat** [comment]
It's even in the client;

![billede](https://user-images.githubusercontent.com/1907820/27755546-97b0a6f2-5df0-11e7-98ee-9abe5b3f42e4.png)

![billede](https://user-images.githubusercontent.com/1907820/27755554-a19467da-5df0-11e7-96cd-68e2c82f3dbc.png)

**Comment by Phatcat** [comment]
On normal server you don't get flagged for pvp on any of the boats going anywhere and on pvp servers it don't matter that it's considered horde territory because there's no way to get on the boat without passing neutral territory which will put everyone in pvp there.

I found a way to consistently cause the game client crash though so I'll move that to the core tracker.
