### ISSUE TITLE
Arathi Dwarven coast farm

### ISSUE THREAD

**Issue by Phatcat** [cmangos/classic-db#9]
0 -1852 -4145 11
http://wow.gamepedia.com/Arathi_coast_dwarven_farm

> Two Dwarven Farmers live on the farm. One patrols the road leading up to the farm. The other one is inside the house, sleeping. Both are marked as Alliance NPCs. Many critters roam around on the farm. Rats hide in the acre, or in the stable. The cats, which there are many of, only sit and watch the rats. There are two rams in the stable as well.

Missing basically everything.

**Comment by Phatcat** [comment]
(All of this got removed in wotlk, btw, so only missing for classic and tbc)

**Comment by Swater96** [comment]
I can look into this, luckily https://www.youtube.com/watch?v=leXm6STvSKM shows NPC names and locations

**Comment by cala** [comment]
Closed by https://github.com/cmangos/classic-db/commit/fb94ef48edf8ae2710c0f8f93e8137d4885ae168
Thanks both of you !
